
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = awww-daemon
exec-once = hyprlock
exec-once = waybar
exec-once = fcitx5 &



exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
exec-once = /usr/bin/lxqt-policykit-agent &
exec-once = xsettingsd &


