##############################
### LOOK AND FEEL (Global) ###
##############################

# Use the absolute path or relative to ~/.config/hypr/
source = ~/.config/hypr/colors.conf

general {
    gaps_in = 3
    gaps_out = 3
    border_size = 3

    # Colors sourced from colors.conf
    col.active_border = $primary $on_primary 45deg
    col.inactive_border = $background

    # Centralized Layout Switch
    layout = scrolling

    resize_on_border = false
    allow_tearing = false
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 10
        render_power = 2
        color = $background
    }

    blur {
        enabled = false
        size = 5
        passes = 3
        vibrancy = 1
    }
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    background_color = $background
}

xwayland {
    force_zero_scaling = true
}
