########################
### MASTER CONFIG    ###
########################

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/env-variables.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/colors.conf

# Visuals & Global Logic
source = ~/.config/hypr/hyprland-decoration.conf
source = ~/.config/hypr/animations.conf

# Input & Interaction
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf

# Rules & Layout specifics
source = ~/.config/hypr/windows-workspaces.conf
