##############################
### WINDOWS AND WORKSPACES ###
##############################

# hypr/windows-workspaces.conf

# Main monitor workspaces (Standard scrolling)
workspace = 1, monitor:$main_monitor, deafult:true
workspace = 2, monitor:$main_monitor
workspace = 3, monitor:$main_monitor
workspace = 4, monitor:$main_monitor
workspace = 5, monitor:$main_monitor

# Side monitor workspaces (Forced full-width)
workspace = 6, monitor:$side_monitor
workspace = 7, monitor:$side_monitor
workspace = 8, monitor:$side_monitor
workspace = 9, monitor:$side_monitor
workspace = 10, monitor:$side_monitor

# --- Layout Specific Settings ---
scrolling {
    direction = right
    column_width = 0.5
    fullscreen_on_one_column = true
}

dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = master
}

monocle {

}
